#ifndef HW_ARDUINO_MEGA_2560_REV3_H
#define HW_ARDUINO_MEGA_2560_REV3_H

/* 16MHz main clock */
#define F_CPU ( 16000000UL )

/* Built-in LED ( D13 ) */
#define INDICATOR_STATUS_SINGLE__PIN ( 7U )
#define INDICATOR_STATUS_SINGLE__PORT ( PORTB )

#endif /* HW_ARDUINO_MEGA_2560_REV3_H */
